### PR TITLE
Fixed issue where plugin breaks post types without editor

### PR DESCRIPTION
**Pull request by magnuspaaske**
Basically this issue: https://github.com/jepser/typeform/issues/4

Checking if there's a media property on the wp object and if there's not, the plugin does nothing. This fixes the issue so e.g. Woocommerce orders don't get broken by this plugin.

Not sure if it should be released in its own version or there are other changes that should be fixed with the same version number so left that out

### CODE REVIEW

**Review by jepser — APPROVED** [review]

**Comment by jepser** [comment]
I will test the branch and let you know, thanks @magnuspaaske

**Comment by magnuspaaske** [comment]
Has this branch been merged and published to the wordpress plugin repository?

**Comment by jepser** [comment]
Sorry about this I will publish the new version by the end of this week. Thanks a lot!

**Comment by jepser** [comment]
https://wordpress.org/plugins/typeform/ There is a new version :)

**Comment by magnuspaaske** [comment]
Awesome :)

**Pull request merged**
